repos:
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v1.5.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.5.4
  hooks:
  - id: isort
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
    args: [--max-line-length=100]
