[project]
name = "fenestra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cups-of-caffeine>=2.9.12",
    "ewmh>=0.1.6",
]
